/**
 * Production entry — boots the BUILT TanStack Start server
 * (`dist/server/server.js`, generated by `vite build`) as a plain Node HTTP
 * server. The build output is a fetch handler (`(request) => Response`), not
 * a listening server; this wrapper is what the Docker image runs.
 *
 *   PORT                listen port (default 8080 — matches the dev server)
 *   HOST                bind address (default 0.0.0.0)
 *
 * The `/api/*` browser proxy lives in `src/server.ts` (built into the same
 * bundle), so no proxy config is needed here.
 */
import { createServer } from "node:http";
import { toNodeHandler } from "h3/node";
import serverModule from "./dist/server/server.js";

const port = Number(process.env.PORT ?? 8080);
const host = process.env.HOST ?? "0.0.0.0";

// The build exports the fetch handler as the default export.
const handler = serverModule.default ?? serverModule;

createServer(toNodeHandler(handler)).listen(port, host, () => {
  console.log(`🚀 Frontend SSR listening on http://${host}:${port}`);
});
